-- drop table CPI

create table CPI (
	"Prov Id" integer,
	"Year" integer,
	"Fresh or frozen meat" float,
	"Fresh or frozen poultry" float,
	"Processed meat" float,
	"Fish, seafood and other marine products" float,
	"Fresh milk" float,
	"Butter" float,
	"Cheese" float,
	"Eggs" float,
	"Bakery products" float,
	"Cereal products" float,
	"Fresh fruit" float,
	"Preserved fruit and fruit preparations" float,
	"Fresh vegetables" float,
	"Preserved vegetables and vegetable preparations" float,
	"Sugar and confectionery" float,
	"Edible fats and oils" float,
	"Coffee and tea" float,
	"Non-alcoholic beverages" float,
	"Food purchased from restaurants" float,
	"Rented accommodation" float,
	"Homeowners replacement cost" float,
	"Property taxes and other special charges" float,
	"Homeowners home and mortgage insurance" float,
	"Homeowners maintenance and repairs" float,
	"Electricity" float,
	"Water" float,
	"Natural gas" float,
	"Fuel oil and other fuels" float,
	"Telephone services" float,
	"Internet access services" float,
	"Child care and housekeeping services" float,
	"Household cleaning products" float,
	"Paper, plastic and aluminum foil supplies" float,
	"Other household goods and services" float,
	"Household furnishings and equipment" float,
	"Clothing" float,
	"Footwear" float,
	"Clothing accessories, watches and jewellery" float,
	"Clothing material, notions and services" float,
	"Purchase, leasing and rental of passenger vehicles" float,
	"Operation of passenger vehicles" float,
	"Gasoline" float,
	"Public transportation" float,
	"Health care" float,
	"Personal care" float,
	"Recreation" float,
	"Education and reading" float,
	"Alcoholic beverages" float,
	"Tobacco products and smokers supplies" float
);

