-- drop table Census;

create table Census (
	"Year" integer,
	"RO Year" integer,
	"FED Id" integer,
	"FED Name" varchar,
	"population age 0-4" integer,
	"population age 5-9" integer,
	"population age 10-14 years" integer,
	"population age 15-17" integer,
	"population age 18-19" integer,
	"population age 20-24" integer,
	"population age 25-29" integer,
	"population age 30-34" integer,
	"population age 35-39" integer,
	"population age 40-44" integer,
	"population age 45-49" integer,
	"population age 50-54" integer,
	"population age 55-59" integer,
	"population age 60-64" integer,
	"population age 70-74" integer,
	"population age 75-79" integer,
	"population age 80-84" integer,
	"population age 85+" integer,
	"couple families with 1 child" integer,
	"couple families with 2 children" integer,
	"couple families with 3 or more children" integer,
	"average num of persons per family" float,
	"private households by household size 1 person" integer,
	"private households by household size 2 persons" integer,
	"private households by household size 3 persons" integer,
	"mother tongue single responses english" integer,
	"mother tongue single responses french" integer,
	"mother tongue multiple responses english and french" integer,
	"knowledge of official languages english only" integer,
	"knowledge of official languages french only" integer,
	"knowledge of official languages english and french" integer,
	"knowledge of official languages neither english nor french" integer,
	"first official language spoken english" integer,
	"first official language spoken french" integer,
	"first official language spoken english and french" integer,
	"first official language spoken neither english nor french" integer,
	"first official language spoken official language minority num" integer,
	"home language spoken single responses english" integer,
	"home language spoken single responses french" integer,
	"population 1 year and over by mobility status 1 year ago movers" integer,
	"populati...over by mobility status 1 year ago migrants 250516AB" integer,
	"populati...obility status 1 year ago internal migrants E5731743" integer,
	"populati... status 1 year ago intraprovincial migrants 9412EDCF" integer,
	"populati...obility status 1 year ago external migrants C5DD2868" integer,
	"canadian citizenship" integer,
	"citizenship other than canadian" integer,
	"population 15+ by generation status 1st generation" integer,
	"population 15+ by generation status 2nd generation" integer,
	"population 15+ by generation status 3rd generation and over" integer,
	"first nations north american indian single identity" integer,
	"métis single identity" integer,
	"inuit single response identity" integer,
	"labour force 15+ by occupation not applicable" integer,
	"labour f...ness finance and administration occupations 2B82C03E" integer,
	"labour f...nd applied sciences and related occupations BF041023" integer,
	"labour force 15+ by occupation health occupations" integer,
	"labour f...pations in art culture recreation and sport E6577C9B" integer,
	"labour force 15+ by occupation sales and service occupations" integer,
	"population aged 15+ by place of work status worked at home" integer,
	"populati... place of work status worked outside canada B2E16A0B" integer,
	"populati...e of work status no fixed workplace address 90CEDF61" integer,
	"populati... place of work status worked at usual place C99B477F" integer,
	"employed...nsportation car truck or van as a passenger 0212B8C0" integer,
	"employed...5+ by mode of transportation public transit B18141EA" integer,
	"employed labour force 15+ by mode of transportation walked" integer,
	"employed labour force 15+ by mode of transportation bicycle" integer,
	"employed...15+ by mode of transportation other methods FC108373" integer
);
